### ISSUE TITLE
some items miss "UI:"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#10]
In listview
![ui--](https://cloud.githubusercontent.com/assets/4154978/24651903/375718c4-1938-11e7-9985-416097d1f8f1.png)

**Comment by kvichans** [comment]
Это спорный случай. Я специально не отнес их к Разделу `UI`.
ИМХО: 
- Раздел `UI` должен содержать опции влияющие на **вид**.
- `ui_non_text` и пр. - это опции про **поведение.**

В целом, когда будет назначен _сопровождающий_, он на свой вкус будет назначать.
Если пройдет идея с новым форматом `default.json`, то вы и будете это делать.
