### ISSUE TITLE
Unneeded debug str

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#103]
On going to default.json option i see

[ 0.07"]OptEdD.do_file:533 to_open=C:\Cudatext\settings_default\default.json
[ 0.09"]OptEdD.do_file:534 ed.get_filename()=C:\Cudatext\settings_default\default.json

**Comment by kvichans** [comment]
Спрячу

**Comment by Alexey-T** [comment]
fixed?
