### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#107]
Как вам идея? 
По кнопке Contents показать окно с списком опций в виде кликабелных линков, клик ведёт к опции в обычном списке. Если показать таблицу компактно. Например в два столбика. И мелким шрифтом. То будет обзор. И таблицу группировать. Чтобы глазами искать имя опции и кликнуть. Пример- как выглядит список хедеров в начале википедии статей .

**Comment by kvichans** [comment]
Не понятно.
1. Каким образом можно показывать двухколоночную таблицу ссылок?
2. Сейчас для ОпцРед показывает 294 опции Куд (у меня). 
Какие из них попадут в Contents, все? Ни при каком *мелком шрифте* они все не будут видны одновременно.
3. Дайте снимок с Википедии.

ИМХО неудачное направление усилий

**Comment by Alexey-T** [comment]
290 опций это слишком много , так что наверно не стоит...
