### ISSUE TITLE
After applying opt, listbox is empty

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#109]
Лин, опция auto_close_brackets

- ввел знач (, ENTER - ок, применилось
- снова октрыл длг
- ввел там же дефолт строку- ([{ , ENTER
==> применилось но листбокс теперь пуст! может глюк Лаза - скроллинг листбокса снова все показал
![screenshot from 2018-10-11 10-28-35](https://user-images.githubusercontent.com/4154978/46787640-d4683400-cd40-11e8-969b-4bbaea26acce.png)

**Comment by kvichans** [comment]
"листбокс" это `Filter`?

**Comment by Alexey-T** [comment]
главный список , listview.

**Comment by kvichans** [comment]
не повторил

**Comment by Alexey-T** [comment]
может это только в Убунту?

**Comment by kvichans** [comment]
не повторил в Убунте

**Comment by Alexey-T** [comment]
локальное или временный глюк лаз.
