### ISSUE TITLE
Apply my workaround for macOS (remove hotkeys 1..9)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#110]
Для мак нам нужно убрать хоткеи 0..9 - там есть глюк который хз когда поправят - ввод цифр в Edit дергает эти хоткеи. понятно что это проблема Лаз. но для юзера нужно поправить

Вот этот дифф в картинке
![screenshot from 2019-01-10 10-56-47](https://user-images.githubusercontent.com/4154978/50954258-e0da6500-14c6-11e9-8742-cd9a00048831.png)

**Comment by kvichans** [comment]
ToDo Уберу только для Мак

**Comment by Alexey-T** [comment]
спасибо, а то делать правку после вашей правки- не ОК

**Comment by kvichans** [comment]
Проверьте из ГХ

**Comment by Alexey-T** [comment]
лучше так проверять ОС
```
>>> import platform
>>> platform.system()
'Darwin'
```

**Comment by kvichans** [comment]
Есть готовая функция, которая распознает **больше** чем platform.system(), буду применять ее.

**Comment by Alexey-T** [comment]
то есть вот
https://docs.python.org/3/library/sys.html#sys.platform

**Comment by Alexey-T** [comment]
А зачем вам "больше чем  platform.system"? надо определить Мак

**Comment by kvichans** [comment]
Универсальные решения лучше специальных.
Проверили? Публиковать?

**Comment by Alexey-T** [comment]
решение /if sys.platform=='darwin'/ НАДЕЖНЕЕ- а ваша ф-я может сбойнуть.

**Comment by kvichans** [comment]
Аргументы с обоих сторон слабые - это дело вкуса.
Публиковать?

**Comment by Alexey-T** [comment]
Да

**Comment by Alexey-T** [comment]
Можете ещё под мак убрать кнопку рудимент- она в правом верхнем углу?

**Comment by kvichans** [comment]
"рудимент"?

**Comment by Alexey-T** [comment]
пустая кнопка без надписи. около кнопки Габмургер.

**Comment by Alexey-T** [comment]
![eeeee](https://user-images.githubusercontent.com/4154978/50971772-ebf8b980-14f5-11e9-8f00-9ff91c1491bf.png)

**Comment by kvichans** [comment]
Нет гипотез, что это за кнопка. Пока не знаю как ее спрятать.
Если нажать, что-нибудь происходит?

**Comment by kvichans** [comment]
Есть подозрение, что она вызывает применение фильтра. Так?

**Comment by kvichans** [comment]
Если "да", то она задается в строке
974 `,('fltr',d(tp='bt' ,cap=''     ,sto=False  ,def_bt='1' ,t=0,l=-99,w=44))  # Enter`
 Попробуйте разные значения у t[op] и l[eft]

**Comment by kvichans** [comment]
Ага, понял. Исправляю

**Comment by kvichans** [comment]
Отрицательные значения для `l` рассматриваются, как отступ от правого края формы.
Вета в ГХ. Лучше?

**Comment by Alexey-T** [comment]
лучше. она пропала, ОК.

ее нажатие не применяло фильтр. она не жалась вроде.

**Comment by kvichans** [comment]
В справке поменял фразы
`Alt+N sorts the N column.`
`Alt+9 resets sorting.`
на 
`Alt+N sorts the N column (not for Mac).`
`Alt+9 resets sorting (not for Mac).`

Good?

**Comment by Alexey-T** [comment]
Alt+N sorts by N-th column (not on macOS).
Alt+9 resets sorting order (not on macOS).

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
точнее
Alt+# (# is 1...9) sorts by #-th column (not on macOS).

**Comment by kvichans** [comment]
ок
