### ISSUE TITLE
zebra option

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#111]
новая пара "опция - АПИ".
"zebra" - PROP_ZEBRA

**Comment by kvichans** [comment]
В чем вопрос/пожелание?
Диалог подхватывает все опции автоматом. Есть проблема?

**Comment by kvichans** [comment]
Ааааа. Новая PROP! Это нужно править в cudax_lib `OPT2PROP = dict`

**Comment by Alexey-T** [comment]
да да, я про это.

**Comment by Alexey-T** [comment]
про cudax_lib- я был против одной новой ф-ции, вы убрали ее тогда?

**Comment by kvichans** [comment]
Про какую функцию?

**Comment by Alexey-T** [comment]
что-то вроде записи опции с новыми параметрами.

**Comment by kvichans** [comment]
1. Нет, не добавлял того, что вы возражали
2. Добавьте сами в OPT2PROP новую пару (опция, PROP) - диалог их похватит

**Comment by Alexey-T** [comment]
наши копии cudax_lib уже расходятся вроде (ГХ). можно привести вашу к моей?

**Comment by kvichans** [comment]
Не расходятся - я пользуюсь версией из сборок Куд

**Comment by Alexey-T** [comment]
добавил в репо Куды.
