### ISSUE TITLE
Special combo for font_name

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#13]
Get all font names
app_proc(PROC_ENUM_FONTS, '')
beta Cud.

**Comment by kvichans** [comment]
Ага. Теперь можно сделать тип font

**Comment by kvichans** [comment]
Нужны пояснения к результату вызова
```
>>> =app.app_proc(app.PROC_ENUM_FONTS, '')
['@Batang', ...'Batang',...]
```
Нужно ли показывать шрифты с именами на `@` ?

**Comment by kvichans** [comment]
Можете ли вы оставить в списке только полезные шрифты?
Я не знаю как это делается, но некоторые приложения показывают сильно сокращенный список для выбора

**Comment by Alexey-T** [comment]
Нет- на моей стороне менять список нельзя- не знаю про "@"
