### ISSUE TITLE
cannot change font size (Linux)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#14]
в моем конфиге не меняется-
```
  "font_name__linux" : "DejaVu Sans Mono",
  "font_size__linux" : 9,
```

**Comment by kvichans** [comment]
Что ж тут странного. Я создавал `default_options.json` из `default.json` месячной давности.
Конечно обновлю.

**Comment by kvichans** [comment]
Рассмотрел свежую версию `default.json`. В ней не нашел ключи
`font_name__linux`
`font_size__linux`
Как так?

**Comment by Alexey-T** [comment]
забыл.НАдо для всех сделать- суффиксы __win __linux __mac. Todo

**Comment by Alexey-T** [comment]
сильно поменял сейчас def.json. См==
последний пач в ГХ

**Comment by kvichans** [comment]
если не сложно, дайте ссылку

**Comment by kvichans** [comment]
нашел

**Comment by Alexey-T** [comment]
Еще один пач для def.json

**Comment by kvichans** [comment]
И когда будет окончательный вариант?
Давайте фиксировать, чтобы я мог предложить перефоматированный вариант.
А потом правьте в вволю

**Comment by Alexey-T** [comment]
Еще пач. это пока все
