### ISSUE TITLE
font_size type ="font"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#17]
Must be int.
ui_font_size is int.

**Comment by kvichans** [comment]
Не вижу.
Может вы спутали с `tags` из 
```
{   "comment": "UI elements font",
        "key": "ui_font_size",
        "def_val": 9,
        "chapter":"UI",
        "tags":["font","env"]
    }
```
?

**Comment by Alexey-T** [comment]
выделенная строчка-

![ff](https://cloud.githubusercontent.com/assets/4154978/24677986/728887d0-1991-11e7-9b22-ece4516f32df.png)

**Comment by kvichans** [comment]
В первом посте вы писали про `ui_font_size`. Он правильный.
`font_size` поправил.
