### ISSUE TITLE
plugin name is not Title Case

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#21]
Pls make Title Case

**Comment by kvichans** [comment]
Зачем это для имени плагина? Где он отображается?
До этого вы просили, чтобы пункт из меню Plugins был CamelCase. Это уже сделано
```
[item10]
section=commands
caption=Options Editor...
method=dlg_cuda_opts
;menu=0
```

**Comment by Alexey-T** [comment]
я просил Title Case. Показывается-- в addon manager в меню

**Comment by kvichans** [comment]
"Title Case" это что?

**Comment by kvichans** [comment]
А-а-а
Вы про 
```
[info]
title=Options editor
```
Поправил
