### ISSUE TITLE
Useful format of default.json to

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_options_editor#22]
Давайте согласовывать то, что задумал внести в `default.json`

1. **Секции.** С секциями будет просто - комментарий после пустой строки такого вида
`  //[Section: Text]`
означает, что дальше все ключи будут из секции Text. Имена секций могут повторяться, то есть не обязательно собирать все ключи в одном месте.
Принято?

2. **Теги.** Предлагаю в любом месте комментария к ключу разрешить конструкцию
`  //Text font name (#font, #text)`
Этого будет достаточно, чтобы достать теги.
Принято?

3. **Формат значения**. 
- Если умоч. значение достаточно для вычисления типа, то ничего указывать не нужно. Так можно получить `bool`, `int`, `float`, `str`, `json`.
- Если в имени ключа есть фрагмент `font_name`, то формат будет `font`
- Если в комментарии есть конструкция
`  //  0: Default`
`  //  1: Draft`
то это `enum_i`. Если
`  //  "": disabled`
`  //  "a": by Alt+click`
то - `enum_s`
- Для формата `file` будет явное указание (еще не придумал как, но для ядра Куд этого не нужно)
Принято?

4. Если у ключа пустой комментарий, то все настройки берутся от предыдущего.
Принято?

**Comment by kvichans** [comment]
5) **Добавления**. Можно сделать так
```
  //Text font name (#font,#text)
  "font_name": "Courier New",
  //...prefer in Linux
  "font_name__linux": "Courier New",
  //...prefer in Mac
  "font_name__mac": "Courier New",
```
То есть если комментарий начинается на `...`, то он добавляется к последнему из комментариев, который НЕ начинается на `...`.
Принято?

**Comment by Alexey-T** [comment]
Про 1, 2, 3 (секции, теги...)- ОК, принято

**Comment by Alexey-T** [comment]
4- (значения)- Принято

**Comment by Alexey-T** [comment]
5- не нужно. Не будет коментов кот. начинаются с "..."

**Comment by kvichans** [comment]
5. Это не будет мешать :). Я заложу в конвертор такую возможность. А вы можете ей не пользоваться.

**Comment by Alexey-T** [comment]
5- OK

**Comment by kvichans** [comment]
Есть проблема определением типа font для ключа
`//Output panel font name`
`  "ui_font_output_name" : "default",`
Тогда будет такое RE для назначения типа: `font\w*_name$`

**Comment by kvichans** [comment]
Опа! Можно назначить тип font, если среди значений есть "default"?
Добавить "default" к списку имен для шрифтов?

**Comment by Alexey-T** [comment]
>Добавить "default" к списку имен

Да

> тип font, если среди значений есть "default"?

нет, нельзя.

**Comment by kvichans** [comment]
Нашел еще ключ, для которого нужен суффикс
```
  //When file opens, and cannot detect encoding, 
  //  open it as "ANSI" (option=false) or "UTF8" (option=true)
  //  Defaults: Windows: false, Linux/macOS: true
  "def_encoding_utf8": false,
```
Сделать?

**Comment by Alexey-T** [comment]
Суфикс надо делать мне- если он нужен тут

**Comment by kvichans** [comment]
Да, конечно. Я добавлю в свой вариант json, а вы в ядро

**Comment by Alexey-T** [comment]
OK; сделаю пач для суфикса

**Comment by Alexey-T** [comment]
> комментарий после пустой строки такого вида//[Section: Text]

Забыл про "section:"- можно поменять формат? просто [Text] а не [Section: Text]. 
?
Если "section:" то это лишний текст.

**Comment by kvichans** [comment]
Fixed
Можно и так и так

**Comment by Alexey-T** [comment]
Ок, пусть [Text], чтобы короче текст
