### ISSUE TITLE
Beta v1.1.0

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_options_editor#23]
1. При каждом запуске из файла `default.json` извлекается инф для отображения.
2. Старый файл частично пригоден для этого
![cudatext options 1 1 0 _old_def](https://cloud.githubusercontent.com/assets/7419630/24708863/cf9e60e0-1a20-11e7-8a6c-0868ae9feb60.png)
- Нет Секций
- Нет Тегов
- Не все значения распознаны корректно
3. Если подменить на мой `kv-default.json` (передал по Тел), то все есть
![cudatext options 1 1 0 _new_def](https://cloud.githubusercontent.com/assets/7419630/24708864/cfa2750e-1a20-11e7-84ba-992be2265a72.png)
4. Дальше любой может вносить в `default.json` изменения соблюдая синтаксис:
- `  //[Section: Text]` - будет Секция
- `(#font,#text)` - будут Теги (в диалоге они в комментарии не отобразятся)
- `  //...` - Продолжение описания

**Comment by Alexey-T** [comment]
Default.json в гх-- имеет секции для всех опций. можно их исп-ть у вас??

**Comment by kvichans** [comment]
Зачем?!

**Comment by Alexey-T** [comment]
Для показа Секций- у меня их нет без вашего kv-def.json

**Comment by kvichans** [comment]
"Мой" _почти_ такой же как ваш. Сравните (могу прислать diff)
Я только явно добавить __linux и __mac ключи
Чуть-чуть поправил комментарии и расставил теги

**Comment by kvichans** [comment]
Если я мой вариант дам как патч, то это будет удобно?

**Comment by Alexey-T** [comment]
Нет пока не надо патч- теги пока нет времени смотреть
