### ISSUE TITLE
wrong value of URL regex show

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#24]
Показывает без всех `\`
![regex---](https://cloud.githubusercontent.com/assets/4154978/24711124/b87d9c80-1a27-11e7-9ad2-01cd9c124b26.png)

**Comment by Alexey-T** [comment]
Value + DefaultValue - д.быть равны

**Comment by kvichans** [comment]
См..

**Comment by kvichans** [comment]
А-а-а. Сообразил - я же вместо json.loads руками значения разбираю. Нужно мета знаки учесть.
