### ISSUE TITLE
new default.json in GH (will be beta)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#25]
Плис, использовать секции в нем, без вашей версии kv-default.json
Пока у меня эти секции не видны

**Comment by kvichans** [comment]
Секции описаны так, как было "согласовано"?

**Comment by Alexey-T** [comment]
В общем так- см файл.

**Comment by kvichans** [comment]
Почти????! Это не ответ. Был согласован формат "  //[Section: Text]"
Под него я сделал программу. Соблюдайте договор
