### ISSUE TITLE
value for "fold" with ","

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#26]
Its bug
![fold--](https://cloud.githubusercontent.com/assets/4154978/24714744/0b4bfa06-1a32-11e7-9db0-feed1fbc7bc3.png)

**Comment by kvichans** [comment]
Нужен файл

**Comment by Alexey-T** [comment]
Это default.json (он уже в ГХ)
еще тут видно ","
![more--](https://cloud.githubusercontent.com/assets/4154978/24715084/09a8395c-1a33-11e7-9b6b-ef26d473ac90.png)

**Comment by kvichans** [comment]
fold_style - не повторил
caret_shape - fixed
