### ISSUE TITLE
wish. show font's Preview label

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#27]
Чтобы показать превью, надо вывести "type=label\1font=nnnnnnnnnnn,10"
"font=" уже в бете.

**Comment by kvichans** [comment]
Забавно. Применю

**Comment by kvichans** [comment]
Понимает ли атрибут `font` значение `default`? Будет?

**Comment by kvichans** [comment]
Толку от такого превью мало, если не ставить сразу же правильный размер.
А как плагин вычислит какой из размеров правильный?

По хорошему, нужно объединить ключи
font_name
font_size
в одну опцию. Только что-то это муторно. Подумаю...

**Comment by Alexey-T** [comment]
> атрибут font значение default? Будет?

да. понимает. Вы можете попробовать.

**Comment by kvichans** [comment]
Получилось :)
![cudatext options 1 1 1 -font-preview](https://cloud.githubusercontent.com/assets/7419630/24744393/99bd7034-1aba-11e7-9b0f-8b77cddbd78d.png)

**Comment by Alexey-T** [comment]
OK.
