### ISSUE TITLE
wish. Show linux/mac keys auto

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#29]
Показывать ключи
bbbb__linux
bbbb__mac
если в конфиге есть ключ bbbb. и у него есть в описании [has suffix]. Там нету ключей для lin/mac. их надо добавить самому.

**Comment by kvichans** [comment]
Я не буду это делать

**Comment by kvichans** [comment]
Значительно удобнее (всем!), если добавить эти ключи прямо в файл

**Comment by kvichans** [comment]
Более того! У этих ключей разные умолчания. Это означает, что их ТОЧНО нужно добавить явно

**Comment by Alexey-T** [comment]
Наверное вы правы.
Посмотрю.
