### ISSUE TITLE
Beta 1.1.4

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_options_editor#31]
1. Добавлено формирование отчета о всех опциях из `user.json` в виде HTML страницы.
Реализация скопирована с адаптацией из плагина `cuda_opts_report`.
2. Если выбран `Target `для лексера, то в отчете будет колонка для него.

---
@Alexey-T Публиковать? У меня больше идей "что улучшить" нет.

**Comment by Alexey-T** [comment]
Под лин слишком малый размер (дефолт надо поменять. знаю про Adjst...)
![si---](https://cloud.githubusercontent.com/assets/4154978/24763630/f9e61f90-1b02-11e7-8a71-bdbd2e5d8d4b.png)

**Comment by Alexey-T** [comment]
Дефолт можно
height of table =300
height of cmt =100

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Публ. после моего релиза -на релизе 1.7.9 работает некрасиво

**Comment by kvichans** [comment]
ок
