### ISSUE TITLE
if current os=Linux 

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#32]
Если text_font_name__mac задан в "dfdfdf dfdfdf", все равно это значение надо показать под лином.

**Comment by kvichans** [comment]
не понял

**Comment by Alexey-T** [comment]
В мак есть шрифт например "Apple nnn".
надо показать значение "Apple nnn:"

**Comment by kvichans** [comment]
Не понял. Плагин никак не использует (и не должен!) инф о платформе.
Что в user.json?

**Comment by Alexey-T** [comment]
Пример 

"font_name__mac": "Merion"
в Лин значение не покажет. Нет шрифта merion.

**Comment by kvichans** [comment]
"значение"? А-а-а. Добавлять к тому списку, что дает АПИ еще и все указанные в ключах.
ОК

**Comment by kvichans** [comment]
Нда! Тонкое место. Тогда можно будет выбрать несуществующий шрифт для другого ключа.
Подумаю..

**Comment by kvichans** [comment]
Получилось :)
![cudatext options 1 1 4 -font-mac](https://cloud.githubusercontent.com/assets/7419630/24793944/890b8cd0-1b8c-11e7-9222-f51cad047712.png)
Имя неизвестного шрифта добавляется (в конец списка) только для того ключа, где оно используется. Остальным оно не доступно.

**Comment by Alexey-T** [comment]
>добавляется (в конец списка) только для того ключа, где оно используется.

Ок, примерно это нужно.
