### ISSUE TITLE
type of caret_shape_ro, _overwrite wrong

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#34]
![ty---](https://cloud.githubusercontent.com/assets/4154978/24764883/7ba9fe7a-1afe-11e7-8f54-85d346473046.png)

**Comment by Alexey-T** [comment]
Надо тип "caret_shape"

**Comment by kvichans** [comment]
Нужен файл. Есть в ГХ?

**Comment by Alexey-T** [comment]
def.json в ГХ.

**Comment by Alexey-T** [comment]
wish. Поправить это. и можно делать релиз. Куд релизен.

**Comment by kvichans** [comment]
Что "это" поправить?

**Comment by kvichans** [comment]
Доверяете мне изменить default.json? Скопировать enum в описание ключей caret_shape_ovr и caret_shape_ro?

**Comment by Alexey-T** [comment]
Нет- сделать определение типа для caret_shape_*

**Comment by kvichans** [comment]
Предлагаете зашить в плагин реакцию на конкретные ключи? Это ужасно.
Лучше придумать общий трюк. Можно дать внутри комментария спец. фразу, чтобы enum переносить. Например, так
```
 //Possible caret shapes:
  //  0: Full block
  //  1: Vert 1 pixels
  //Caret: shape for normal state
  "caret_shape": 1,
  //Caret: shape for overwrite state (Ins key: insert/overwrite) 
  //(as caret_shape)
  "caret_shape_ovr": 0,
```
Плагин будет распознавать `//(as ref-key)` и брать enum из ref-key.
Делать?

**Comment by Alexey-T** [comment]
"(like ref-key)". Да- делать.

**Comment by Alexey-T** [comment]
Только 1.8 выпущена. без трюка. Для нее бы поправить

**Comment by kvichans** [comment]
Я не буду зашивать конкретный ключ в плагин.
Сделаю перенос enum по фразе `(like ref-key)`.
