### ISSUE TITLE
Hide Type?

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_options_editor#37]
@Alexey-T
Будет лучше, если из таблицы убрать колонку `Type`?

**Comment by kvichans** [comment]
Перечислимые форматы и так нельзя ввести не правильно
Числовые форматы я контролирую (попробуйте ввести не число)
Строковые не нужно контролировать

Удалить?

**Comment by Alexey-T** [comment]
Да, можно удалить

**Comment by Alexey-T** [comment]
Нужно делать тип caret_shape для 3х опций

**Comment by kvichans** [comment]
"делать"? кому?

**Comment by Alexey-T** [comment]
wish.
Если имя ключа caret_shape\w* -то плаг дает ему тип caret

**Comment by kvichans** [comment]
Условие очень широкое
Может быть так:
- Если внутри ключа обнаружен фрагмент "__": `start__end`
- и у этого ключа нет комментария
- и есть ключ `start` с комментарием
- то перенести комментарий (а значит и тип и м.б. перечисление) в `start__end`

**Comment by Alexey-T** [comment]
У caret_share_ro нет условия на "__"...

**Comment by kvichans** [comment]
Нужен строгий алгоритм для действий общего вида. Ваш
>Если имя ключа caret_shape\w* -то плаг дает ему тип caret

не общего вида
