### ISSUE TITLE
Fold-style er

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#39]
Для опц. не показывает значение в комбо
и запятая после "1"
![fold--](https://cloud.githubusercontent.com/assets/4154978/24813650/ec84882c-1bdf-11e7-90c8-9431349e2698.png)

**Comment by kvichans** [comment]
Не вижу такого:
![cudatext options 1 1 8 -fold](https://cloud.githubusercontent.com/assets/7419630/24816124/484095ac-1be0-11e7-98d6-1cb1509242b6.png)

Файл есть на ГХ?

**Comment by Alexey-T** [comment]
файл из релиза 1.8.

**Comment by kvichans** [comment]
1. Вижу недооформленый ключ
```
  //Keys PageUp/PageDown page size:
  //  0: full height; 1: full minus 1; 2: half height
  "key_page_size": 1,
```
Должно быть
```
  //Keys PageUp/PageDown page size:
  //  0: full height
  //  1: full minus 1
  //  2: half height
  "key_page_size": 1,
```

2. Оформление ключа
```
  //Minimap: Width
  //  0: autosize
  //  >0: fixed width in chars
  "minimap_char_width": 0,
```
неудачное. Будет сформирован enum {0: autosize}

3. Проблема с fold_style была в пробелах после "1,". 
Fixed

**Comment by Alexey-T** [comment]
Fixed описание из 1.
Для 2 сделал
```
  //Minimap: Width
  //  value=0: autosize
  //  value>0: fixed width in chars
  "minimap_char_width": 0,
```

**Comment by Alexey-T** [comment]
Для 2. как надо описать?

**Comment by kvichans** [comment]
Я еще по дороге исправил две серьезные ошибки конвертора
- не распознавалось значение "-5"
- не распознавался enum_s для ключа mouse_goto_definition

---
>Для 2. не помогло..

Нужен файл

**Comment by Alexey-T** [comment]
Для 2 поправил так
```
  //Minimap: Width
  //  value=0: autosize
  //  value>0: fixed width in chars
  "minimap_char_width": 0,
```
не помогло

**Comment by kvichans** [comment]
Не понимаю. Парсер требует пробела перед "0:".
См..

**Comment by kvichans** [comment]
Да, нормально - целое получается. Что "не помогло"?

**Comment by Alexey-T** [comment]
Нужно- чтобы показывало тип int- счас это enum из 1 эл

**Comment by kvichans** [comment]
на 1.1.9?

**Comment by Alexey-T** [comment]
Ok- fixed
