### ISSUE TITLE
show lowercase "true/false" in table

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#42]
В json - lowercase, а в питон- Titlecase.

**Comment by kvichans** [comment]
Зачем???

**Comment by Alexey-T** [comment]
Чтобы показывать как обычно в json

**Comment by kvichans** [comment]
А кто-то обещал показывать как в json? И строки нужно в кавычках писать?

**Comment by kvichans** [comment]
И кавычки внутри строк экранировать?

**Comment by Alexey-T** [comment]
OK
