### ISSUE TITLE
spaces in Adjust dlg

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#43]
"min___20"- 3 spaces
"min__55"- 2 spaces

**Comment by kvichans** [comment]
Вам показалось :)
![adjust](https://cloud.githubusercontent.com/assets/7419630/24820736/3e75773c-1bf3-11e7-9956-6ffe63fc2471.png)

**Comment by Alexey-T** [comment]
Почему - там 2 и 3 пробела

**Comment by kvichans** [comment]
Где? Вот код вызова dlg_input_ex:
```
, _(       'Width of * (min  20)')
, _(   'Width of Value (min 250)')
, _('Height of Comment (min  55)')
```

**Comment by Alexey-T** [comment]
Ок- по 2 пробела
В лин это так
![sp](https://cloud.githubusercontent.com/assets/4154978/24821051/70b8ddf6-1bfd-11e7-9720-07d3ee7ab6d8.png)

**Comment by kvichans** [comment]
Ну да, только показалось
![adjust-lin](https://cloud.githubusercontent.com/assets/7419630/24821095/43280ea0-1bf5-11e7-985c-6760c108a684.png)

**Comment by Alexey-T** [comment]
зачем 2 пробела...
