### ISSUE TITLE
plugin name on AddonManager

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#46]
Need "Options Editor" like install.inf has
![opt](https://cloud.githubusercontent.com/assets/4154978/24923223/91c1854e-1ef9-11e7-9efe-68d2dddddbb8.png)

**Comment by kvichans** [comment]
Где нужно поменять?

**Comment by Alexey-T** [comment]
Имя файла (SF.net) и строку в https://github.com/kvichans/CudaText-registry/blob/master/registry-addons.txt

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
fixed.
