### ISSUE TITLE
v 1.1.14 Start with user's keys

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_options_editor#47]
Добавлена галка `Altered first`, по которой переставляются ключи в основной таблице: сначала идут ключи из user.json (в том порядке, как они там расположены), а потом все остальные из def.json
![cudatext options 1 1 14 - altered](https://cloud.githubusercontent.com/assets/7419630/25339143/5c9422ee-290a-11e7-95b1-8643de0d022f.png)

@Alexey-T Фразы нормальные?
`Altered first` (у галки)
`Begin list with altered keys in order from user file` (в подсказке)

**Comment by Alexey-T** [comment]
"Show changed first", "changed first"
"Show changed keys from user.json on top of entire list"

**Comment by kvichans** [comment]
Нужно учесть при выборе фраз, что тут есть тонкость - в начальной части списка, составленного из ключей user.json будут **не только** измененные (см. на снимке есть без *), но и с умолчательными значениями. Я пытался передать с помощью `altered` намек, что эти те ключи, которые были изменены, а не только сейчас изменены.

**Comment by Alexey-T** [comment]
Можно тогда "Show configured first"

**Comment by kvichans** [comment]
Длинно! Show можно убрать?

**Comment by Alexey-T** [comment]
"Configured on top"

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Еще нужно в подсказке указать, что порядок ключей будет как в user.json
Как это вставить в ваш вариант `Show user keys on top of entire list`?

**Comment by Alexey-T** [comment]
", the order of keys will be the same as in user.json"

**Comment by kvichans** [comment]
спасибо
