### ISSUE TITLE
Select theme in combo

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#49]
Хочется выбирать тему из combobox
(список папок в data/sideicons,
новая опц- список папок в data/codetreeicons)

![theme--](https://cloud.githubusercontent.com/assets/4154978/25740606/e6e8c336-318f-11e7-8221-607fe89104c6.png)

**Comment by kvichans** [comment]
Одного имени ключа `ui_sidebar_theme` не хватит, чтобы диалог смог понять как набрать из имен файловой системы варианты.
Давайте добавим в комментарий подсказку
```
//...
// Folders from: data/codetreeicons
//...
```
Если значение задано не полным путем, то диалог добавит начало. 
Чем дополнить: папка с самим Куд или что-то другое?

**Comment by Alexey-T** [comment]
Там ведь уже подсказка dir inside "...."

**Comment by Alexey-T** [comment]
Дополнять из папки APP_DIR_DATA

**Comment by kvichans** [comment]
Нынешние комментарий
`//Name of sidebar icon theme (subdir inside data/sideicons)`
не удобен для парсинга. Он оформлен в свободном стиле.
Я готов добавить распознавание подсказки, занимающей всю строку
`// Folders from: data/codetreeicons`

Делаем?

**Comment by Alexey-T** [comment]
Ок- делаем

**Comment by kvichans** [comment]
Жду обновления def.json (достаточно на ГХ)

**Comment by Alexey-T** [comment]
Сделал-
`//Folders from: ..`

**Comment by kvichans** [comment]
Бета.
В вашем def.json две таких конструкции. Но в 
```
Tree: Icons theme
Folders from: data/codetreeicons
```
ссылка в никуда. Сообщение про это попадает в консоль.

**Comment by Alexey-T** [comment]
В бете будет эта codetreeicons.

**Comment by kvichans** [comment]
Это никак не мешает работе диалога.
Если нет указанной папки, формируется простой тип - можно вводить руками как раньше

**Comment by Alexey-T** [comment]
ОК, спасибо

**Comment by Alexey-T** [comment]
список такой-

octocons_20x20: octicons_20x20
octocons_24x24: octicons_24x24

Wish: не надо дубль

**Comment by kvichans** [comment]
Да, это я занес в ToDo
