### ISSUE TITLE
Folder combo dont work

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#52]
для опции нет выбора папки.

![fold](https://cloud.githubusercontent.com/assets/4154978/26013410/e7fba3f2-3760-11e7-8a45-dd180a93ff13.png)

**Comment by kvichans** [comment]
У меня отображается выбор из двух вариантов.
У вас нарушены какие-то условия из соглашения. 
Передайте def_sett.json и содержимое data\sideicons.

**Comment by Alexey-T** [comment]
default.json тут с коментами
//Folders from
видно на скрине.
data/sideicons - папки есть.
Лог

Python 3.5.2
Loading icons: LibreOffice_24x24
[ 0.02"]parse_cmnt:1524 No folder "data/codetreeicons" from
Tree: Icons theme
Folders from: data/codetreeicons
[ 0.05"]parse_cmnt:1524 No folder "data/sideicons" from
Sidebar icons theme
Folders from: data/sideicons

**Comment by Alexey-T** [comment]
Прога в /usr/.....
данные в ~/.cudatext/data/..

**Comment by kvichans** [comment]
Видимо нарушено _соглашение_ о том, что папка `data` находится внутри папки, где лежит исполняемый файл. 
Что показывает ваша консоль при вызове
`=os.path.isdir(os.path.join(app_path(APP_DIR_EXE), 'data/sideicons'))`
?

**Comment by Alexey-T** [comment]
уже 2 года exe file в Лин лежит в /usr/.., а данные в ~/.cudatext.
Показывает False
Надо брать APP_DIR_DATA

**Comment by kvichans** [comment]
_Соглашение_ было. Вы мне явно сказали брать APP_DIR_EXE. Видимо упустили Лин при этом
ToDo

**Comment by kvichans** [comment]
Так как я **не** живу в Лин, для меня не очевидно, что папки
-  `/usr/..`
- `~/.cudatext`

**разные**

**Comment by Alexey-T** [comment]
может, я писал про APP_DIR_DATA...

**Comment by Alexey-T** [comment]
Пач не ОК. app_dir_data не на том же уровне как app_dir_exe, надо брать от него basedir().

**Comment by kvichans** [comment]
Зачем вы критикуете. Просто ответьте на исходный вопрос: как получить на всех платформах доступ к data?

**Comment by Alexey-T** [comment]
сорри. Получить вот так- app_path(APP_DIR_DATA)

**Comment by kvichans** [comment]
В последней версии на ГХ/СФ `app.app_path(app.APP_DIR_DATA)`.
Вы ее взяли?

**Comment by Alexey-T** [comment]
конечно.

**Comment by kvichans** [comment]
Не понимаю проблему

**Comment by kvichans** [comment]
Может быть **на Лин** APP_DIR_DATA это сама папка data?

**Comment by Alexey-T** [comment]
соглашение.
Вы сказали- писать в def.json "data/sideicons".

**Comment by kvichans** [comment]
Почему у меня нормально работает?

**Comment by Alexey-T** [comment]
не знаю. поправил так -
![fix](https://cloud.githubusercontent.com/assets/4154978/26023987/d2a331c6-37d0-11e7-94b8-096b1efca4d2.png)

**Comment by kvichans** [comment]
Нет, я это не приму

**Comment by kvichans** [comment]
Поясните почему app_path(APP_DIR_DATA) 
- на Вин дает правильную папку
- на Лин - неправильную

?

**Comment by Alexey-T** [comment]
Проверил на лин -
>>> =app_path(APP_DIR_DATA)
/home/user/.cudatext/data

дает ОК...

**Comment by kvichans** [comment]
Ага. Понял корень проблемы: у меня `os.path.isdir('data/sideicons')` дает True из-за **случайного** использования тек.папки приложения. Понятно как исправлять код.
Но нужно еще исправить данные.
Предлагаю убрать из def.json фрагменты `data/`

**Comment by Alexey-T** [comment]
Хорошо, если вы советуете

**Comment by kvichans** [comment]
Руками убрал `data/`. У меня работает

**Comment by Alexey-T** [comment]
Fixed
