### ISSUE TITLE
Wish: show status on apply

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#53]
Применение опций- показать в консоль `Options Editor: applied "opt1", "opt2", "opt3"`

**Comment by kvichans** [comment]
Так в _консоль_ или в _статус?_

**Comment by Alexey-T** [comment]
в консоль.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Сделал и туда и туда

**Comment by kvichans** [comment]
Публиковать?

**Comment by Alexey-T** [comment]
Да, пож-та
