### ISSUE TITLE
String of n chars: cannot set it

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#54]
![fullsc](https://cloud.githubusercontent.com/assets/4154978/26120452/795635f4-3a79-11e7-9a5f-8a96dddda252.png)

**Comment by kvichans** [comment]
Тут сразу две проблемы
- Формат сбит
- Из-под комбо выглядывает еще контрол

ToDo

**Comment by kvichans** [comment]
Формат поправил

**Comment by Alexey-T** [comment]
Fixed
