### ISSUE TITLE
error-values for themes, Mac

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#55]
Mac: data dir is ~/.cudatext/data
![mac-many](https://cloud.githubusercontent.com/assets/4154978/26267142/3bc92640-3cf1-11e7-9f69-e415d89ef255.png)

**Comment by kvichans** [comment]
Показывает консоль для 
`=os.listdir( os.path.join(app.app_path(app.APP_DIR_DATA), 'sideicons') )`

**Comment by Alexey-T** [comment]
показыват все эти файлы. Они от old Cud. надо убирать _файлы_

**Comment by kvichans** [comment]
todo
