### ISSUE TITLE
Wish: buttons

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#56]
Wish-
кнопки Report/Close двинуть вверх,
на их место раздвинуть мемо.

**Comment by kvichans** [comment]
Это лишнее. Через Adjust можно увеличить ширину.
Потом это будет просто драг

**Comment by Alexey-T** [comment]
ширину это да, хочется кнопки на одно место.

**Comment by kvichans** [comment]
Нет
