### ISSUE TITLE
Er in GUI on Mac

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#58]
- открыл плагин. выделился пункт font_name.
- Value combo где имя фонта: видно что лежит на чемто еще, тк рамка жирная...
Скрин не нужен. уже вы видели это.

- фокусирую font_size: все равно видно combobox -теперь пустое- поверх ввода числа.
Число ввести нельзя.

1.1.20

**Comment by Alexey-T** [comment]
А, это релиз, он устарел. тогда можно обновить релиз??

**Comment by kvichans** [comment]
Опубликована последняя версия.
Давайте снимок - будем разбираться заново

**Comment by Alexey-T** [comment]
Мак запускать долго, там на месте обычного комбо видна рамка от чего-то сзади , рамка получ двойная. Может это глюк лаза. Непонятно

**Comment by Alexey-T** [comment]
На лине тоже не редактируется font-size

**Comment by kvichans** [comment]
не повторил

**Comment by Alexey-T** [comment]
В гх уже версия ок, значит на СФ старая

**Comment by Alexey-T** [comment]
Юзерам надо на СФ

**Comment by kvichans** [comment]
Проверил - на ГХ и на СФ одинаковые версии

**Comment by Alexey-T** [comment]
Не вижу, обновление из адонмана делает опять баг

**Comment by kvichans** [comment]
поймайте разницу

**Comment by Alexey-T** [comment]
Сравнил файлы, все разное , версии cdpluglib 1.2.2, 1.3.02

**Comment by kvichans** [comment]
"все"?
вижу разницу только в cd_plug_lib.py
но пока не понимаю как она может сказаться

**Comment by Alexey-T** [comment]
Может конечно

**Comment by Alexey-T** [comment]
В ней баг в старой 1.2

**Comment by kvichans** [comment]
ок, обновляю СФ

**Comment by Alexey-T** [comment]
Ок
