### ISSUE TITLE
unneeded spaces in labels

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#6]
In dlg:
![spa](https://cloud.githubusercontent.com/assets/4154978/24614591/4d9f433a-1894-11e7-8d86-f4196606e7c1.png)

**Comment by Alexey-T** [comment]
Dlg title: pls "Adjust"

**Comment by kvichans** [comment]
>unneeded spaces in labels

Что это значит?

Adjust - OK

**Comment by Alexey-T** [comment]
Больше 1 пробела подряд в label

**Comment by kvichans** [comment]
А-а-а. Ясно. Это осталось в тех времен, когда подписи в dlg_input_ex были прижаты в лево.
Да, теперь можно писать без трюков
