### ISSUE TITLE
New options [18] findkey_

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#60]
Нужен новый ввод для них через dlg_hotkey

**Comment by kvichans** [comment]
Да, хорошее дело.

1. Только мне не хочется реагировать на подстроку `findkey_`.
Потом могут появится другие настройки, требующие вызова `dlg_hotkey()`. 
На что можно опереться? Может у имен ключей будет подходящая подстрока? Например, если ключи будут иметь вид `*dlg_hotkey*`, то есть они будут похожи на
```json
  "dlg_hotkey_find_dlg": "Ctrl+F",
  "dlg_hotkey_replace_dlg": "Ctrl+R",
  "dlg_hotkey_find_first": "Alt+Enter",
  "dlg_hotkey_find_next": "Enter",
```
Тогда этого достаточно.

2. Как и кто сможет отследить конфликты? Если пользователь назначит одинаковые сочетания на несколько команд, то что будет?

---
Правильно я понимаю, что внутри диалога ПоискЗамена хоткеи локальные - они не могут вызвать глобальные команды?

**Comment by Alexey-T** [comment]
Можно искать подстроку `_hotkey_`

**Comment by kvichans** [comment]
Годится. Делаю..

**Comment by Alexey-T** [comment]
>они не могут вызвать глобальные команды?

Да

**Comment by kvichans** [comment]
Требуется тестирование

**Comment by Alexey-T** [comment]
Работает - ок

**Comment by kvichans** [comment]
Публикую
