### ISSUE TITLE
Need fix control v-pos

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#63]
Label 'value'/ 'default value' need fix of v-pos
![anch](https://user-images.githubusercontent.com/4154978/27500834-d9f3b4c4-5872-11e7-8abf-64a1124a62ec.png)

**Comment by Alexey-T** [comment]
+btn [...] ширину надо в 2 раза больше.

**Comment by kvichans** [comment]
1. Верт выравнивание зависит от платформы. Покажите снимок диалога, который выз из Фиф по Ctrl+Adj
2. Почему?

**Comment by Alexey-T** [comment]
1- Тогда решено
2- текст в поле маленкий, кнопку надо сделать видной

**Comment by kvichans** [comment]
2. Не понял. Какой текст "маленький"?

**Comment by Alexey-T** [comment]
Текст хоткея, alt+z

**Comment by kvichans** [comment]
2. Не понял: вы про ширину кнопки [...] или про ширину edit? Сейчас нормально все отображается

**Comment by Alexey-T** [comment]
Про ширину кнопки, сделать её шире в 2р

**Comment by kvichans** [comment]
Я бы ее уже на 2 п сделал
Итого - пусть так будет
