### ISSUE TITLE
Two pane dialog, like ST3 Settings command

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#66]
Wish, like in ST3
Preferences - Settings

**Comment by kvichans** [comment]
Можете дать снимок?

**Comment by Alexey-T** [comment]
это "как две группы".
диалог поверх самого Суб.

![su](https://user-images.githubusercontent.com/4154978/30454048-a8a17c54-99a3-11e7-9b62-0c8cb5b2a701.png)

**Comment by kvichans** [comment]
Не понял идею

**Comment by Alexey-T** [comment]
если вы думаете в Суб неудобно, то не надо.
