### ISSUE TITLE
show "false", "true" lowercase

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#68]
Like in JSON
Also in console log lines "changed option ..... to False".

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
Пач примерно такой

**Comment by Alexey-T** [comment]
Перед                 app.msg_status( f(_('Change in {}: "{}": {}'), trgt_s, key_sel, repr(new_val)))
добавить if type(new_val) is bool: new_val = repr(new_val).lower()

**Comment by Alexey-T** [comment]
Точнее вот такие строки
                if new_val==True: new_val='true'
                if new_val==False: new_val='false'

**Comment by kvichans** [comment]
Исправил
Опубликовал
