### ISSUE TITLE
V2, label "For"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#73]
лабел криво выровнен-
![e1](https://user-images.githubusercontent.com/4154978/39359234-d928c4f2-4a21-11e8-8c23-6110c0b1cd56.png)

**Comment by kvichans** [comment]
Вижу. И не только этот. User/Default тоже не встали
Кликните на "=" с зажатым Ctrl. Покажите диалог

**Comment by Alexey-T** [comment]
этот длг дает креш - и в нем внизу radiobtn не двигается.
![ex](https://user-images.githubusercontent.com/4154978/39359658-88d2af02-4a23-11e8-9d7c-6eb19aae5c42.png)

**Comment by kvichans** [comment]
Видно, почему For не на месте - в вас 1, 2, 5 и последняя пары не выровнены.

А креш поймаем. Повторил
И радио-баттон починим.

**Comment by kvichans** [comment]
Креш и радио-баттон починил. Выложил в ГХ

**Comment by Alexey-T** [comment]
radbtn двигается. но опции длг не сохраняются. For не двигается. длг открылся опять старый.

**Comment by kvichans** [comment]
Я забыл сказать, что выравнивание будет применено при следующем запуске ОпРе

**Comment by Alexey-T** [comment]
тепер "user" кривая
![e4](https://user-images.githubusercontent.com/4154978/39363143-ef3472b8-4a31-11e8-96a9-0ca7877330f0.png)

**Comment by kvichans** [comment]
Показывайте новое состояние после Ctrl+"="

**Comment by Alexey-T** [comment]
оно сбросилось. поправил- вышел из плагина- из Куд- запустил- опять сбросилось. когда сохранится то покажу что поправил.

**Comment by kvichans** [comment]
Для каждого *подвинутого* контрола в user.json добавляется ключ, начитающийся с dlg_wrapper_fit_va_for_
Например, у меня 
    "dlg_wrapper_fit_va_for_combo_ro": -4,
    "dlg_wrapper_fit_va_for_combo": -3,

**Comment by Alexey-T** [comment]
вот user.json- диалог его не меняет или не читает

[user.zip](https://github.com/kvichans/cuda_options_editor/files/1955525/user.zip)

**Comment by kvichans** [comment]
Попробуйте изменить через осн.диалог ОпРед какую-нибудь опцию с целым значением. Есть изменение в user.json?

**Comment by kvichans** [comment]
Или попробуйте из консоли
import cudax_lib
cudax_lib.set_opt("dlg_wrapper_fit_va_for_combo",-3)
Есть изменение в user.json?

**Comment by Alexey-T** [comment]
в консоли сработало, есть -3

**Comment by Alexey-T** [comment]
стало работать. хз что. может что-то в файле было не ок.

**Comment by kvichans** [comment]
Уф :)

**Comment by Alexey-T** [comment]
solved

**Comment by kvichans** [comment]
Покажите снимки ОпРед с разными наборами контролов. Желательно задать лексер и ввести в поле User текст
