### ISSUE TITLE
V2, color of statusbar

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#74]
Вы ставите статусбару обыч цвет. для темной темы- получится темный статус на белом окне.
чтобы пофиксить это- вам надо дать статусу цвет видимо такой.
это систем цвет, он не из темы Куд, он из темы ОС - цвет кнопки

COLOR_BTNFACE = 0x8000000F

для шрифта можно black- 0x0.

**Comment by kvichans** [comment]
Нет. Я не задаю для статуса цвет. Вы видите умолчательный. 
По-хорошему, это Куд должен позаботиться о согласовании цветов
