### ISSUE TITLE
V2, btn "font value" not aligned

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#78]
для фонта поле неровно. хотя для чисел поле ровно.
![font--](https://user-images.githubusercontent.com/4154978/39377386-9e061000-4a5d-11e8-8446-e2904e8aef1e.png)

**Comment by Alexey-T** [comment]
для enum тоже криво.

**Comment by kvichans** [comment]
Показывайте снимок после Ctrl+"="

**Comment by Alexey-T** [comment]
Там все выровнено

**Comment by kvichans** [comment]
не верю

**Comment by kvichans** [comment]
Сделайте снимок на новой версии
![default](https://user-images.githubusercontent.com/7419630/39392190-4d3d8682-4aba-11e8-8d43-3ef0c59ba91e.png)

**Comment by Alexey-T** [comment]
![ff](https://user-images.githubusercontent.com/4154978/39393443-e9d98078-4acd-11e8-9e26-4208afb6d33a.png)

**Comment by kvichans** [comment]
Ага! Сообразил, что здесь не выравнивание сбоит, а привязки к краям панели.
Давайте тестировать на репро.
Что у вас при таком запуске?
```python
idd=dlg_proc(0, DLG_CREATE)

idc=dlg_proc(idd, DLG_CTL_ADD,"panel")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'name':'ptop'
,'x':0, 'y':0, 'w':636, 'h':270, 'h_min':270
,'tab_stop':False, 'tab_order':10, 'sp_l':0, 'sp_r':0, 'sp_t':0, 'sp_b':0, 'sp_a':0, 'align':5
,'val':''
,'tp':'pn'})

idc=dlg_proc(idd, DLG_CTL_ADD,"label")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'name':'ed_s'
,'x':5, 'y':210, 'w':70, 'h':14, 'cap':'Us&er:', 'hint':'ui_non_text', 'p':'ptop'
,'tab_order':-1, 'ex0':True, 'sp_l':0, 'sp_r':0, 'sp_t':60, 'sp_b':46, 'sp_a':0, 'a_t':None, 'a_b':('ptop', ']')
,'tp':'lb', 't':210, 'l':5, 'a':'TB'})

idc=dlg_proc(idd, DLG_CTL_ADD,"combo_ro")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'name':'edcb', 'act':True
,'x':78, 'y':206, 'w':288, 'h':22, 'cap':'(1) open in editor', 'p':'ptop'
,'vis':True, 'tab_order':5, 'sp_l':78, 'sp_r':270, 'sp_t':64, 'sp_b':42, 'sp_a':0, 'a_l':('ptop', '['), 'a_r':('ptop', ']'), 'a_t':None, 'a_b':('ptop', ']')
,'val':1, 'items':"(0) show question message\t(1) open in editor\t(2) don't open\t(3) open in viewer, binary mode\t(4) open in viewer, hex mode"
,'tp':'cbr', 'l':78, 'r':366, 'tid':'ed_s', 'a':'TBlR'})

dlg_proc(idd, DLG_PROP_SET, prop={'x':645, 'y':66, 'w':636, 'h':411, 'cap':'CudaText options (2.1.4)', 'tag':''
,'resize':True, 'w_min':636, 'h_min':411})
dlg_proc(idd, DLG_SHOW_MODAL)
dlg_proc(idd, DLG_FREE)
```

**Comment by Alexey-T** [comment]
![dd](https://user-images.githubusercontent.com/4154978/39394010-fffda72e-4ad4-11e8-990b-014ee67d3951.png)

**Comment by kvichans** [comment]
Есть смещение. 
У меня это выглядит так
![default](https://user-images.githubusercontent.com/7419630/39394032-56c725b2-4ad5-11e8-8af4-e03c8da56104.png)
Ваш combo_ro сместился *вверх* (не *вниз* как в ОпРед, видимо из-за другого окружения).
Пробуем на таком (привязка к форме, а не к панели)
```python
idd=dlg_proc(0, DLG_CREATE)

idc=dlg_proc(idd, DLG_CTL_ADD,"label")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'name':'ed_s'
,'x':5, 'y': 10, 'w':70, 'h':14, 'cap':'Us&er:'
,'ex0':True, 'sp_l':0, 'sp_r':0, 'sp_t':60, 'sp_b':46, 'sp_a':0, 'a_t':None, 'a_b':('', ']')})

idc=dlg_proc(idd, DLG_CTL_ADD,"combo_ro")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'name':'edcb', 'act':True
,'x':78, 'y':  6, 'w':288, 'h':22
,'sp_l':78, 'sp_r':270, 'sp_t':64, 'sp_b':42, 'sp_a':0, 'a_l':('', '['), 'a_r':('', ']'), 'a_t':None, 'a_b':('', ']')
,'val':0, 'items':"(0) show question message"})

dlg_proc(idd, DLG_PROP_SET, prop={'x':645, 'y':66, 'w':636, 'h':80, 'cap':'Test'
,'resize':True})
dlg_proc(idd, DLG_SHOW_MODAL)
dlg_proc(idd, DLG_FREE)
```

**Comment by Alexey-T** [comment]
![ddd](https://user-images.githubusercontent.com/4154978/39394126-a77febdc-4ad6-11e8-9588-7fe4a02b68bc.png)

**Comment by kvichans** [comment]
Пока есть сдвиг. Еще упростим. 
```python
idd=dlg_proc(0, DLG_CREATE)

idc=dlg_proc(idd, DLG_CTL_ADD,"label")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'cap':'Us&er:','x':5, 'w':70
, 'y': 10
, 'h':14
, 'sp_t':60
, 'sp_b':46
, 'a_t':None
, 'a_b':('', ']')
})

idc=dlg_proc(idd, DLG_CTL_ADD,"combo_ro")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'val':0, 'items':"message", 'x':78, 'w':288
, 'y':  6
, 'h':22
, 'sp_t':64
, 'sp_b':42
, 'a_t':None
, 'a_b':('', ']')
})

dlg_proc(idd, DLG_PROP_SET, prop={'x':645, 'y':66, 'w':636, 'h':80, 'cap':'Test'})
dlg_proc(idd, DLG_SHOW_MODAL)
dlg_proc(idd, DLG_FREE)
```

**Comment by kvichans** [comment]
Убедимся, что корень проблемы в привязках
```python
idd=dlg_proc(0, DLG_CREATE)

idc=dlg_proc(idd, DLG_CTL_ADD,"label")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'cap':'============','x':5, 'w':70
, 'y': 10
, 'h':14
#, 'sp_t':60
#, 'sp_b':46
#, 'a_t':None
#, 'a_b':('', ']')
})

idc=dlg_proc(idd, DLG_CTL_ADD,"combo_ro")
dlg_proc(idd, DLG_CTL_PROP_SET, index=idc, prop={'val':0, 'items':"============", 'x':78, 'w':288
, 'y':  6
, 'h':22
#, 'sp_t':64
#, 'sp_b':42
#, 'a_t':None
#, 'a_b':('', ']')
})

dlg_proc(idd, DLG_PROP_SET, prop={'x':645, 'y':66, 'w':636, 'h':80, 'cap':'Test'})
dlg_proc(idd, DLG_SHOW_MODAL)
dlg_proc(idd, DLG_FREE)
```
Ожидаю такого
![default](https://user-images.githubusercontent.com/7419630/39394281-0887e464-4ad9-11e8-8ec5-c253bc9372bf.png)

**Comment by Alexey-T** [comment]
да- у меня тоже ровно.
по пред. коду--
![d4](https://user-images.githubusercontent.com/4154978/39394387-59643fa8-4ada-11e8-8ede-c85ed26d1f68.png)

**Comment by kvichans** [comment]
Нет, у вас есть сдвиг. Удалите коменты в последнем коде - будет очевидно

**Comment by Alexey-T** [comment]
сдвиг в 1-2 пк максимум

**Comment by Alexey-T** [comment]
еще такой эфект.
открытие на опции font_*- размер value field низкий - как у edit.
потом клик на другой опции фонта- размер стал большой, хороший.

**Comment by kvichans** [comment]
>сдвиг в 1-2 пк максимум

Если вам все равно, зачем настраиваем? Может и начальная картинка вас устраивает?

Дайте снимки эффекта "низкий/большой"

**Comment by Alexey-T** [comment]
мне не все равно- я ответил что "ровно как у вас- плюс минус 1 пиксел".

**Comment by Alexey-T** [comment]
![screenshot from 2018-04-28 13-29-59](https://user-images.githubusercontent.com/4154978/39395525-4a9e1378-4ae8-11e8-9bd1-a6397543e6d0.png)
![screenshot from 2018-04-28 13-30-03](https://user-images.githubusercontent.com/4154978/39395528-4ea486b4-4ae8-11e8-8b8d-a80cd1569afe.png)

**Comment by kvichans** [comment]
Вроде вижу, что на первом снимке combo не касается edit, а на втором касается.
Лучше бы на втором снимке была точно такая же ситуация как на первом - такое же заполение combo.
Нет идей. Код после показа этих контролов не меняет их размеры. Единственное (из размеров), что иногда меняет код - это ширины колонок и высоту memo.
