### ISSUE TITLE
V1 don't change user.json now

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#80]
после юзания Вер2.

**Comment by kvichans** [comment]
У меня старых ОпРед меняет json
Дайте пример - попробую

**Comment by Alexey-T** [comment]
пример - опция find_separate_form не меняется.

**Comment by kvichans** [comment]
У меня V1 нормально меняет find_separate_form
Может быть опять что-то общее мешает изменять user.json? После перезапуска Куд V1 работает?

**Comment by Alexey-T** [comment]
руками-то я поправил- рид онли нет. нет.

**Comment by kvichans** [comment]
>после юзания Вер2.

В пределах тек.запуска Куд?

**Comment by Alexey-T** [comment]
ну да

**Comment by kvichans** [comment]
Критическое место. Лучше дискорд

**Comment by Alexey-T** [comment]
можно проверить- если заптсь в юзер не идет ==при пустом табе без лексера== то это баг set_opt. он  fixed.
