### ISSUE TITLE
Wish for menuitems

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#81]
предлагаю 3 п-та в Plugins:

Options Editor\Dialog, standard...
Options Editor\Dialog, modern...
Options Editor\Configure UI control alignments... 
(что делает Ctrl+click on '=')

**Comment by kvichans** [comment]
Не нужно в глоб.меню
- Старый диалог сохранится, но будет вызываться
- Configure UI добавлю в лок.меню диалога

**Comment by Alexey-T** [comment]
а эти 2 пункта как?
Options Editor\Dialog, standard...
Options Editor\Dialog, modern...

**Comment by kvichans** [comment]
Не нужны, так как будет применяться только один.

**Comment by Alexey-T** [comment]
один пункт из Plugins уберется? ок.

**Comment by kvichans** [comment]
В Plugins останется единственный вызов уже на след.неделе.

Upd. Сегодня оказывается уже среда :). Значит на *этой* недели старый диалог будет спрятан.
