### ISSUE TITLE
V2, mac aligns bad

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#82]
![mac2](https://user-images.githubusercontent.com/4154978/39418474-49adde90-4c63-11e8-97a3-a1f157c4a709.png)
![mac-ee](https://user-images.githubusercontent.com/4154978/39418476-4cae8df6-4c63-11e8-8223-fe78ff278f9f.png)

**Comment by kvichans** [comment]
Нужно копать "привязки к границам" - там есть темные места. Жаль, что у меня нет виртуальных ОС

**Comment by Alexey-T** [comment]
sp_t sp_b  у вас вроде юзаются вместе для 1 контрола. это отступ от края анкора и сверху и снизу. лучше делать анкор только один- верх или низ (тогда и sp_ юзается один)

**Comment by kvichans** [comment]
Хорошо - попробую

**Comment by kvichans** [comment]
Есть идея! Могу сам один раз найти высоты контролов.
Для это нужно вызвать скрытый диалог с этими контролами, сразу его закрыть и взять живые размеры.

**Comment by kvichans** [comment]
Получится обертка над GUI_HEIGHT

**Comment by Alexey-T** [comment]
лучше так не делать, тормоза появятся.

**Comment by kvichans** [comment]
Почему тормоза? Один раз за текущий вызов Куд - разве это много?

**Comment by kvichans** [comment]
На моей ОС все и так работает. Это я пытаюсь ваши Лин/Мак/Вин10 поправить. Сами ядро исправите?

**Comment by Alexey-T** [comment]
не могу поправить.

**Comment by kvichans** [comment]
Для реализации задуманного нужно после вызова DLG_SHOW_MODAL закрыть диалог без участия пользователя. Пока не могу сообразить, как это сделать. Есть идеи?

**Comment by kvichans** [comment]
Хотя... В этом случае можно попробовать вызывать DLG_SHOW_NONMODAL. Ни разу этого еще не делал. Какие при этом нужно соблюдать правила? Можно ли сразу после DLG_SHOW_NONMODAL доступаться к контролам?

**Comment by Alexey-T** [comment]
можно - сразу после show читать контролы.

**Comment by kvichans** [comment]
Пробую...

**Comment by kvichans** [comment]
Можно тестировать версию ГХ на Лин/Мак/...

**Comment by Alexey-T** [comment]
после кликов - метка User все равно выше своего комбо. не помогло. лучше убрать хак.
теперь еще вывод в консоль.

**Comment by Alexey-T** [comment]
даже не после кликов- а сразу при показе- для опций font_name метка user выше ем надо.

**Comment by kvichans** [comment]
Почему убрать? Нужно копать дальше - что там происходит

**Comment by kvichans** [comment]
Дискорд?
