### ISSUE TITLE
Release Candidat version

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_options_editor#83]
Вроде, новый диалог готов к публикации.
Проверяем...

**Comment by Alexey-T** [comment]
плохо с выравниванием- уже в вин10 (Лин то же самое)
![align](https://user-images.githubusercontent.com/4154978/39534512-6a85591c-4e3a-11e8-85a4-85b111c61c00.png)

**Comment by kvichans** [comment]
Нда :( 
Это происки *привязок*. Есть подозрения. Завтра их проверим

**Comment by kvichans** [comment]
Выложил второй Release Candidat.
Изменения только при вызове из ФиФ
