### ISSUE TITLE
Checked (*)false while must be (*)true

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#84]
на другом ПК видел что для дефолт опций нет отметки ни false ни true.
а на этом есть- но не та.
![screenshot from 2018-05-03 21-02-28](https://user-images.githubusercontent.com/4154978/39594498-7ffc6732-4f15-11e8-9989-26bd5b6d34b9.png)

**Comment by Alexey-T** [comment]
а тут - та
![screenshot from 2018-05-03 21-05-32](https://user-images.githubusercontent.com/4154978/39594590-c5926f94-4f15-11e8-9d3c-9f84c034fd34.png)

**Comment by kvichans** [comment]
Может быть вкл настройку ALL в меню и выделили опц без умолч?

**Comment by Alexey-T** [comment]
настройку не включал. только выделил.

**Comment by kvichans** [comment]
Может было [x]User?

**Comment by kvichans** [comment]
Стоп! Радио-кноп никогда не отображают умолч значение

**Comment by Alexey-T** [comment]
значит GTK2 форсит.

**Comment by Alexey-T** [comment]
форсит выделение в радио-кноп.

**Comment by kvichans** [comment]
Может быть ошибка плага при смене опц
