### ISSUE TITLE
reduntant message

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#85]
![screenshot from 2018-05-03 21-07-07](https://user-images.githubusercontent.com/4154978/39594654-fb8c3530-4f15-11e8-8429-640788931a11.png)

**Comment by kvichans** [comment]
Ну да, согласен. Предложите формулировку. Надо пулучить подтв, что дальше будет применяться умолч знач.

**Comment by Alexey-T** [comment]
надо __не показывать вообще, если значение юзер == дефолту и я жму Ресет

**Comment by kvichans** [comment]
Не согласен

**Comment by kvichans** [comment]
Надо явно сказать какое значение с какого уровня будет дальше применяться.

ToDo
