### ISSUE TITLE
Add info labels

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#86]
когда я выбрал опция НЕ меняемую для таба-
вместо value combobox покажите лабел "Option cannot be changed for file"

когда выбрал [x]Lexer и не выбрал лекс, 
вместо val combo покажите лабел "Choose lexer first".

**Comment by kvichans** [comment]
>когда я выбрал опция НЕ меняемую для таба-
>вместо value combobox покажите лабел "Option cannot be changed for file"

Показываю edit для значения и делаю его недоступным

---
>когда выбрал [x]Lexer и не выбрал лекс,
>вместо val combo покажите лабел "Choose lexer first".

Фокус попадает на комбо с лексерами. Контролы для значений недоступны

---
Итого - уже продумано

**Comment by Alexey-T** [comment]
счас- не понятно. потом и предл. сделать инфо лабелы.

**Comment by kvichans** [comment]
Подумаю

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Дополнительно сделал `en=False` для `[ ]File`, если опция не регулируется для таба.
Не планирую др.изменения в этом направлении.
