### ISSUE TITLE
Console message "Change in user.json: nnnnn: nnnnn"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#87]
надо вернуть сообщение.

**Comment by kvichans** [comment]
Не понятно на что ссылаетесь.
Чего не хватает?

**Comment by Alexey-T** [comment]
Версия1 при изменении опции писала в консол строку
Change in user.json: "ui_nnnnn": false

**Comment by kvichans** [comment]
Писать протокол изменений?

**Comment by Alexey-T** [comment]
да- как версия1.

**Comment by kvichans** [comment]
Забудьте про V1 :)

**Comment by kvichans** [comment]
ToDo
