### ISSUE TITLE
Plugin don't apply settings

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#89]
V2 диалог не применяет опции на лету- как делал длг Вер.1.

не могу поменять опцию у которой дефолт=тру. чекбокс уже чекед на "фалс", из-за линукс, и нажать это "фалс" не могу

**Comment by kvichans** [comment]
Как называется опция?

**Comment by kvichans** [comment]
А если сначала поставить true, а потом false, то "меняет на лету"?

**Comment by Alexey-T** [comment]
Не меняет

**Comment by Alexey-T** [comment]
Опция любая булево с дефолтом тру.

**Comment by kvichans** [comment]
Значит есть надежда отладить

**Comment by Alexey-T** [comment]
например опция "показать ruler".

**Comment by Alexey-T** [comment]
например меняю  minimap_show = миникарта не меняется. это должно быть даже без опции File?

**Comment by Alexey-T** [comment]
Вер2 НЕ вызывает команду "settings: reload/apply config" которая меняла на лету

**Comment by kvichans** [comment]
>Опция любая

Ага! Все-таки речь про перекрытие файловых опций.
Изменение на уровне user/lexer НЕ должно СЕЙЧАС приводить к перенастройке тек.файла.

Хотя это иногда нужно. Сделаю запрос "Поменять и для тек.файла?" ToDo

**Comment by kvichans** [comment]
>команду "settings: reload/apply config"

ToDo

**Comment by Alexey-T** [comment]
PullReq - fixed.

**Comment by kvichans** [comment]
>не могу поменять опцию у которой дефолт=тру. чекбокс уже чекед на "фалс", из-за линукс, и нажать это "фалс" не могу

Это отдельная проблема?
Поясните "из-за линукс"

**Comment by Alexey-T** [comment]
да, отдельная проблема. Это из за того что линукс форсит отметку хотя бы в одном radio button

**Comment by Alexey-T** [comment]
Pull req примените плис

**Comment by kvichans** [comment]
PR не приму. 
- Вызов `ed.cmd(cmds.cmd_OpsReloadAndApply)` сделаю, конечно такой же
- Но _отчет о действиях_ буду формировать по-другому

**Comment by kvichans** [comment]
>линукс форсит отметку хотя бы в одном radio button

Это неожиданно. Придется переделать на два check-а

---
Заодно избавлюсь от проблемы с TabStop-ами для этих радио. Они теряют положение в цикле обхода Табом, если невидимы.
