### ISSUE TITLE
use type=filter_listview

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#9]
Для верхнего контрола "фильтр". это быстрее чем edit.

**Comment by Alexey-T** [comment]
И добавить need API>=1.0.174

**Comment by kvichans** [comment]
Попробую. Только наверно История отвалится. Это для меня важная фишка

**Comment by kvichans** [comment]
Пока оч.много [проблем](https://github.com/Alexey-T/CudaText/issues/786#issuecomment-291476969).
