### ISSUE TITLE
Font_name_i needs empty val

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#94]
пустое значение для опции font_name_i / font_name_b / font_name_bi нужно- значит что такой фонт не исп-тся - пока плагин не дает задать пустое. это из беты 1.53.

**Comment by kvichans** [comment]
Это *криво*! Можно ли переделать не ОпРед, а новые опции, чтобы не путать теплое с мягким?

**Comment by Alexey-T** [comment]
а как их переделать? вводить опции "исползовать такой то фонт"? это будет криво.

**Comment by kvichans** [comment]
Поясните, что это за опции

**Comment by kvichans** [comment]
Например, значение Default можно использовать вместо *пустого*

**Comment by Alexey-T** [comment]
ну default тут тоже имеет смысл- это дефолт-фонт ОСи - и пустое это другое.

**Comment by kvichans** [comment]
Переделать ОпРед можно. Но есть проблема в блоке, который выполняет вычисление типа по имени опции и ее комментарию.
Вы предложили **новый тип** - _имя шрифта или пустое значение_, который до этого не применялся. Нужно для него ввести новый *договор* и может быть изменить описание внутри default.json.
Предыдущий договор для моего *блока* был такой: если в имя опции входит `'font\w*_name'`, то это имя шрифта.

---
Вы так и не пояснили, где применяются новые опции.

**Comment by Alexey-T** [comment]
внутри def.json для этих 3х опций поменял текст- это ок?
```
  //Text font name, for "italic" fragments [has suffix]
  //Empty str: not used
  "font_name_i": "",
  "font_name_i__linux": "",
  "font_name_i__mac": "",

  //Text font name, for "bold" fragments [has suffix]
  //Empty str: not used
  "font_name_b": "",
  "font_name_b__linux": "",
  "font_name_b__mac": "",

  //Text font name, for "bold+italic" fragments [has suffix]
  //Empty str: not used
  "font_name_bi": "",
  "font_name_bi__linux": "",
  "font_name_bi__mac": "",

```

**Comment by kvichans** [comment]
Запутали! или запутались?
Написали `Empty str: not used`, а говорили, что как раз для этих нужны пустые значения.

**Comment by kvichans** [comment]
А-а-а. Запутали :)
Это сообщение не для моего блока, а для пользователя.
Какой новый договор?

**Comment by Alexey-T** [comment]
пусть пустое разрешается по тексту "Empty string is allowed". сейчас поменяю так.

**Comment by kvichans** [comment]
Хорошо буду ждать наличие строки `Empty string is allowed` в коменте

**Comment by Alexey-T** [comment]
в ГХ уже так сделано.

**Comment by kvichans** [comment]
взял

**Comment by kvichans** [comment]
Как протестировать эти опции?

**Comment by kvichans** [comment]
Тестируем

**Comment by Alexey-T** [comment]
не сработало для опций font_name_i__linux font_name_i__mac.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Тестируем дальше

**Comment by Alexey-T** [comment]
теперь нормально.
