### ISSUE TITLE
UI topic

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#95]
@kvichans передам Ваш ответ--

---
А что в новом OptionEditor происходит (по логике автора) на даблклик ПКМ по выделенной строке с опцией?
То, ЧТО у меня происходит - я толком и описать не могу. Какие-то прыжки по списку вверх/вниз, то на 20 опций, то на 3....
Смена выделения строки ещё плюсом к этому... в общем - ересь хоруса))))
 
P.S. и все же - почему динамически поиск не реализован? Как в смартфоне? Набрал пару символов - и подходящее под это сразу отфильтровывается и показывается в общем списке.Символ добавил - и новый фильтр применился. С ENTER'ом всегда прилетает мысль - что сейчас весь диалог с автоподтверждением всех сделанных правок закроется и амба!

**Comment by kvichans** [comment]
Странное поведение по ДвКлику (но не правой, а левой мышкой) подтверждаю - будет исправление.
Сделаю опцию для обновления списка при каждом изменении фильтра. Сам ей пользоваться не буду, так как отвалится История поисков, которой активно пользуюсь

**Comment by kvichans** [comment]
В ГХ выложил версию позволяющую перейти на мгновенный поиск
![default](https://user-images.githubusercontent.com/7419630/40003764-d608412a-579c-11e8-88e0-e0aea316a57e.png)
При этом
- Содержимое таблицы меняется при каждом изменении фильтра
- История не сохраняется. Более того, комбо все время пустой. (При отключении галки в меню, содержимое комбо восстанавливается и накопление продолжается дальше)
- ВВОД продолжает работать для перехода в таблицу. Еще можно переходить ТАБом

**Comment by Alexey-T** [comment]
лучше назвать Instant filtering.

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
можно релиз чтобы я написал что легко обновить?

**Comment by Alexey-T** [comment]
Предлагаю в историю-
- added menu item “= / More / Instant filtering”, which activates instant updating of list, on typing filter text

**Comment by Alexey-T** [comment]
More... - точки не надо, они значат что откроется окно

**Comment by Alexey-T** [comment]
Q:

 
P.S. "All options from User/Lexer" - а эта фича ЧТО делает такого? В моем случае визуально я не вижу никаких отличий в её вкл./выкл. состояниях...
P.P.S. может стоит все же Справку делать или в HTML-полном виде или в chm формате? С картинками, подписями, ссылками, .... всякой нужной атрибутикой, помогающей яснее понять - ЧТО и КАК надо/можно менять? И поясняющей КАЖДЫЙ пункт/элемент во всех меню/диалогах этого плагина?
 
ИМХО: Вообще странно, что для плагинов нет такой обязаловки что ли, по которой плагин будет добавлен в общий плагринг))))=хостинг плагинов, только если у него будет полноценная справка, хотя бы в виде полноценных тултипов ко ВСЕМ элементам. Очень странно, что везде практически подразумевается, что плагин очень самодостаточно о себе сам "говорит". Мол, все элементы/пункты понятны и так....

**Comment by kvichans** [comment]
1. Некоторые плагины, например ФИФ, хранят часть/все свои настройки в user.json. Поэтому там со временем накапливаются ключи, который нет в def.json
2. Справедливо. Не хватает контрола с *rich-format* содержимым, например, RTF (не дай бог!) или вики (мне нра) или HTML (сильно избыточный). Я бы давал справки в него.

**Comment by kvichans** [comment]
1. Как это описать в Help?

**Comment by Alexey-T** [comment]
1. Some plugins store their settings into user.json. So after a while, user.json contains options not present in default.json. To see all these keys, use plugin option "All options from User/Lexer".

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Опубликовал
