### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#96]
переключил Instant.
диалог не закрывал. инстант не работает (после закрытия-откр длг - работает).
и статусбар уехал вверх.

![screenshot from 2018-05-15 11-14-47](https://user-images.githubusercontent.com/4154978/40044888-6d0c9e88-5831-11e8-8d29-4eaedb5b768a.png)

**Comment by kvichans** [comment]
ок, будет применяться после перевызова

**Comment by Alexey-T** [comment]
клик по Istant== стабильно статусбар уежает вверх.

**Comment by kvichans** [comment]
Обновил ГХ и СФ
