### ISSUE TITLE
Weird sort

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#97]
кликнул сорт по секции. ожидаю что "имя" будет сортировано тоже. но нет- 
![screenshot from 2018-05-15 11-22-53](https://user-images.githubusercontent.com/4154978/40045280-88b5c9ba-5832-11e8-959d-a81e950974ad.png)

**Comment by kvichans** [comment]
Как это? Чего ожидали?

**Comment by kvichans** [comment]
Можно сделать как в ТС: клик по заголовку колонки с зажатым Ctrl добавляет эту колонку к сортировке. Заморочно реализовывать, но интересно
