### ISSUE TITLE
Statusbar inf

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#98]
лучше показать

- Total: nnn
- Visible: mm

или 1 cell

- Visible mm of nnn

**Comment by kvichans** [comment]
Не понял

**Comment by Alexey-T** [comment]
лучше показать в статусбар 2 панелки

- "Total: число всех"
- "Visible:  число видимых"

**Comment by kvichans** [comment]
Вроде так и показываю. Только текст убран в тултип

**Comment by Alexey-T** [comment]
идея- показать и текст- места полно.

**Comment by kvichans** [comment]
Нет. Сейчас удобнее
