### ISSUE TITLE
Win10 150% scaled not fixed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#99]
- buttons tiny
- checkbox pos bad

![win](https://user-images.githubusercontent.com/4154978/40045743-c97bee9c-5833-11e8-91eb-8d2c09030778.png)

**Comment by kvichans** [comment]
Нда уж - еще нахлебаемся с этим скейлом

**Comment by kvichans** [comment]
Разное поведение чеков Lexer и File! Нет идей как это возможно

**Comment by Alexey-T** [comment]
File портится на втором! вызове диалога. на первом- ОК.

**Comment by Alexey-T** [comment]
а почему кнопки малы, как вы их скалируете?

**Comment by kvichans** [comment]
Сдвиг File на втором вызове повторил в Вин7. Поразительно, но интересно - есть что исследовать.
Кнопки? Я их теперь(!) не трогаю - у них должны быть размеры от ОС. Есть сомнения? Дайте примеры нормальных

**Comment by Alexey-T** [comment]
т.е. кнопки не скалируете- вот и малы. можно скалировать по x/y? (или Куд мешает)

**Comment by kvichans** [comment]
Тогда придется на каждой ОС выяснять какие из контролов поддаются скалированию. Очевидно не все. 
Все запутаннее и запутаннее. Может дать опцию, чтобы показывать **нескалированный** диалог? Я проверил - это работает.

**Comment by Alexey-T** [comment]
- не надо такой опции, это для юзера не хор.
- скалировать можно все (кроме  image?)- и кнопки

**Comment by kvichans** [comment]
- Если выбирать между "кривая раскладка" и "мелкая раскладка", я бы на месте пользователя выбрал второе

**Comment by kvichans** [comment]
- Перекос пофиксил - выложил в ГХ
- Про мелкие кнопки нужно прояснить.
